export const allProducts = {
  groceries: [
    {
      id: 1,
      title: "Organic Greenhouse Tomatoes New 18kg",
      image: "/image/product/photo1.webp",
      secondImage: "/image/product/photo13.jpg",
      price: 160,

      discountPrice: 120,
      discount: 47,
      rating: 100,
      reviews: 2,
      seller: "Robert's Store",
      badge: "sale",
      brand: "Razer",
      category: "groceries",
      liked: true,
    },
    {
      id: 2,
      title: "Australian Large Granny Smith Apples",
      image: "/image/product/photo2.webp",
      secondImage: "/image/product/photo7.jpg",
      price: 350,
      discountPrice: 200,
      rating: 100,
      reviews: 1,
      seller: "Young Shop",
      badge: "new",
      brand: "Razer",
      category: "groceries",
    },
    {
      id: 3,
      title: "Australian Choice Red Capsicum New 3kg",
      image: "/image/product/photo3.webp",
      secondImage: "/image/product/photo13.jpg",
      price: 266,
      rating: 93,
      reviews: 4,
      seller: "Global Office",
      brand: "Razer",
      category: "groceries",
      liked: true,
    },
    {
      id: 4,
      title: "Australian Choice Cavendish Bananas",
      image: "/image/product/photo4.webp",
      secondImage: "/image/product/photo15.jpg",
      price: 266,
      rating: 100,
      reviews: 1,
      seller: "Robert's Store",
      brand: "Razer",
      category: "groceries",
      liked: true,
    },
    {
      id: 5,
      title: "Choice Australian Broccoli News 20kg",
      image: "/image/product/photo5.jpg",
      secondImage: "/image/product/photo16.jpg",
      price: 666,
      rating: 100,
      reviews: 1,
      seller: "Young Shop",
      brand: "Razer",
      category: "groceries",
    },
    {
      id: 6,
      title: "Baby White Washed Potatoes New 15kg",
      image: "/image/product/photo6.jpg",
      secondImage: "/image/product/photo11.jpg",
      price: 300,
      discountPrice: 230,
      rating: 100,
      reviews: 1,
      seller: "Robert's Store",
      brand: "Razer",
      category: "groceries",
    },
  ],
  smartwatch: [
    {
      id: 7,
      title: "Apple Watch Series 9 GPS 45mm",
      image: "/image/product/photo7.jpg",
      secondImage: "/image/product/photo7.jpg",
      price: 429,
      originalPrice: 499,
      discount: 14,
      rating: 95,
      reviews: 128,
      seller: "Tech Store",
      badge: "sale",
      brand: "Razer",
      category: "smartwatch",
    },
    {
      id: 8,
      title: "Samsung Galaxy Watch 6 Classic",
      image: "/image/product/photo8.jpg",
      secondImage: "/image/product/photo8.jpg",
      price: 399,
      rating: 92,
      reviews: 85,
      seller: "Samsung Official",
      badge: "new",
      brand: "Razer",
      category: "smartwatch",
    },
    {
      id: 9,
      title: "Garmin Forerunner 965 GPS",
      image: "/image/product/photo9.jpg",
      secondImage: "/image/product/photo9.jpg",
      price: 599,
      rating: 98,
      reviews: 67,
      seller: "Sports Tech",
      brand: "Razer",
      category: "smartwatch",
    },
    {
      id: 10,
      title: "Fitbit Versa 4 Health & Fitness",
      image: "/image/product/photo10.jpg",
      secondImage: "/image/product/photo10.jpg",
      price: 199,
      originalPrice: 249,
      discount: 20,
      rating: 88,
      reviews: 156,
      seller: "Fitness Hub",
      badge: "sale",
      brand: "Razer",
      category: "smartwatch",
    },
    {
      id: 21,
      title: "Amazfit GTR 4 Smart Watch",
      image: "/image/product/photo11.jpg",
      secondImage: "/image/product/photo11.jpg",
      price: 199,
      rating: 90,
      reviews: 45,
      seller: "Amazfit Store",
      brand: "Razer",
      category: "smartwatch",
    },
    {
      id: 22,
      title: "Huawei Watch GT 3 Pro",
      image: "/image/product/photo12.jpg",
      secondImage: "/image/product/photo12.jpg",
      price: 329,
      originalPrice: 399,
      discount: 18,
      rating: 89,
      reviews: 67,
      seller: "Huawei Official",
      badge: "sale",
      brand: "Razer",
      category: "smartwatch",
    },
  ],
  computer: [
    {
      id: 11,
      title: "MacBook Pro 14-inch M3 Chip",
      image: "/image/product/photo13.jpg",
      secondImage: "/image/product/photo13.jpg",
      price: 1999,
      originalPrice: 2199,
      discount: 9,
      rating: 96,
      reviews: 89,
      seller: "Apple Store",
      badge: "sale",
      brand: "Razer",
      category: "computer",
    },
    {
      id: 12,
      title: "Dell XPS 13 Plus Laptop",
      image: "/image/product/photo1.jpg",
      secondImage: "/image/product/photo1.jpg",
      price: 1299,
      rating: 91,
      reviews: 124,
      seller: "Dell Official",
      badge: "new",
      brand: "Razer",
      category: "computer",
    },
    {
      id: 13,
      title: "Gaming Desktop RTX 4080 32GB RAM",
      image: "/image/product/photo1.jpg",
      secondImage: "/image/product/photo1.jpg",
      price: 2499,
      rating: 94,
      reviews: 76,
      seller: "Gaming Pro",
      brand: "Razer",
      category: "computer",
    },
    {
      id: 14,
      title: "iPad Pro 12.9-inch M2 Chip",
      image: "/image/product/photo1.jpg",
      secondImage: "/image/product/photo1.jpg",
      price: 1099,
      originalPrice: 1199,
      discount: 8,
      rating: 93,
      reviews: 203,
      seller: "Tech World",
      badge: "sale",
      brand: "Razer",
      category: "computer",
    },
    {
      id: 23,
      title: "ASUS ROG Zephyrus G14 Gaming Laptop",
      image: "/image/product/photo1.jpg",
      secondImage: "/image/product/photo1.jpg",
      price: 1499,
      originalPrice: 1699,
      discount: 12,
      rating: 95,
      reviews: 87,
      seller: "ASUS Store",
      badge: "sale",
      brand: "Razer",
      category: "computer",
    },
    {
      id: 24,
      title: "Microsoft Surface Laptop 5",
      image: "/image/product/photo1.jpg",
      secondImage: "/image/product/photo1.jpg",
      price: 1299,
      rating: 90,
      reviews: 65,
      seller: "Microsoft Store",
      brand: "Razer",
      category: "computer",
    },
  ],
  sport: [
    {
      id: 15,
      title: "Nike Air Max 270 Running Shoes",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 150,
      originalPrice: 180,
      discount: 17,
      rating: 89,
      reviews: 245,
      seller: "Nike Store",
      badge: "sale",
      brand: "Razer",
      category: "sport",
    },
    {
      id: 16,
      title: "Adidas Ultraboost 22 Sneakers",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 190,
      rating: 92,
      reviews: 178,
      seller: "Adidas Official",
      badge: "new",
      brand: "Razer",
      category: "sport",
    },
    {
      id: 17,
      title: "Wilson Pro Staff Tennis Racket",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 249,
      rating: 95,
      reviews: 67,
      seller: "Sports Equipment",
      brand: "Razer",
      category: "sport",
    },
    {
      id: 18,
      title: "Under Armour Gym Bag 40L",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 89,
      originalPrice: 120,
      discount: 26,
      rating: 87,
      reviews: 134,
      seller: "Under Armour",
      badge: "sale",
      brand: "Razer",
      category: "sport",
    },
    {
      id: 19,
      title: "Yoga Mat Premium Non-Slip 6mm",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 45,
      rating: 91,
      reviews: 289,
      seller: "Wellness Store",
      brand: "Razer",
      category: "sport",
    },
    {
      id: 20,
      title: "Resistance Bands Set with Handles",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 29,
      originalPrice: 39,
      discount: 26,
      rating: 88,
      reviews: 156,
      seller: "Fitness Pro",
      badge: "sale",
      brand: "Razer",
      category: "sport",
    },
  ],
};

export const categories = [
  { id: "groceries", label: "Groceries" },
  { id: "smartwatch", label: "Smart Watch" },
  { id: "computer", label: "Computer" },
  { id: "sport", label: "Sport" },
];

// *********************************************************************************************

// export const allProducts = {
//   groceries: Array.from({ length: 15 }, (_, i) => {
//     const basePrice = +(5 + i * 0.5).toFixed(2);
//     const hasDiscount = i % 4 === 0;

//     return {
//       id: 1 + i,
//       title: `Organic Fruit Pack #${i + 1}`,
//       image: `https://images.pexels.com/photos/${1059909 + i}/pexels-photo-${
//         1059909 + i
//       }.jpeg`,
//       secondImage: `https://images.pexels.com/photos/${
//         1059909 + i
//       }/pexels-photo-${1059909 + i}.jpeg`,
//       price: basePrice,
//       rating: +(4 + (i % 5) * 0.1).toFixed(1),
//       reviews: 10 + i * 3,
//       seller: `Farm ${i % 3}`,
//       badge: hasDiscount ? "sale" : i % 5 === 0 ? "new" : undefined,
//       originalPrice: hasDiscount
//         ? +(basePrice + 1 + i * 0.1).toFixed(2)
//         : undefined,
//       discount: hasDiscount ? 10 + i : undefined,
// brand: "Razer",
// category: "groceries",
//     };
//   }),

//   smartwatch: Array.from({ length: 15 }, (_, i) => {
//     const basePrice = +(150 + i * 10).toFixed(2);
//     const hasDiscount = i % 3 === 0;

//     return {
//       id: 16 + i,
//       title: `Smartwatch Model ${i + 1}`,
//       image: `https://images.pexels.com/photos/${267394 + i}/pexels-photo-${
//         267394 + i
//       }.jpeg`,
//       secondImage: `https://images.pexels.com/photos/${
//         267394 + i
//       }/pexels-photo-${267394 + i}.jpeg`,
//       price: basePrice,
//       rating: +(3.5 + (i % 6) * 0.3).toFixed(1),
//       reviews: 20 + i * 5,
//       seller: `Tech Shop`,
//       badge: hasDiscount ? "sale" : i % 4 === 0 ? "new" : undefined,
//       originalPrice: hasDiscount ? +(basePrice + 20).toFixed(2) : undefined,
//       discount: hasDiscount ? 15 + i : undefined,
// brand: "Razer",
// category: "smartwatch",
//     };
//   }),

//   computer: Array.from({ length: 15 }, (_, i) => {
//     const basePrice = +(800 + i * 50).toFixed(2);
//     const hasDiscount = i % 4 === 0;

//     return {
//       id: 31 + i,
//       title: `Laptop Series ${i + 1}`,
//       image: `https://images.pexels.com/photos/${18105 + i}/pexels-photo-${
//         18105 + i
//       }.jpeg`,
//       secondImage: `https://images.pexels.com/photos/${
//         18105 + i
//       }/pexels-photo-${18105 + i}.jpeg`,
//       price: basePrice,
//       rating: +(4 + (i % 5) * 0.1).toFixed(1),
//       reviews: 30 + i * 2,
//       seller: `Computer Store`,
//       badge: hasDiscount ? "sale" : i % 5 === 0 ? "new" : undefined,
//       originalPrice: hasDiscount ? +(basePrice + 100).toFixed(2) : undefined,
//       discount: hasDiscount ? 12 + i : undefined,
// brand: "Razer",
// category: "computer",
//     };
//   }),

//   sport: Array.from({ length: 15 }, (_, i) => {
//     const basePrice = +(30 + i * 5).toFixed(2);
//     const hasDiscount = i % 4 === 0;

//     return {
//       id: 46 + i,
//       title: `Sport Gear ${i + 1}`,
//       image: `https://images.pexels.com/photos/${2529148 + i}/pexels-photo-${
//         2529148 + i
//       }.jpeg`,
//       secondImage: `https://images.pexels.com/photos/${
//         2529148 + i
//       }/pexels-photo-${2529148 + i}.jpeg`,
//       price: basePrice,
//       rating: +(3.5 + (i % 6) * 0.3).toFixed(1),
//       reviews: 15 + i * 4,
//       seller: `Sports Brand`,
//       badge: hasDiscount ? "sale" : i % 5 === 0 ? "new" : undefined,
//       originalPrice: hasDiscount ? +(basePrice + 10).toFixed(2) : undefined,
//       discount: hasDiscount ? 10 + i : undefined,
// brand: "Razer",
// category: "sport",
//     };
//   }),
// };

// export const categories = [
//   { id: "groceries", label: "Groceries" },
//   { id: "smartwatch", label: "Smart Watch" },
//   { id: "computer", label: "Computer" },
//   { id: "sport", label: "Sport" },
// ];
