export const allProducts = {
  groceries: [
    {
      id: 1,
      name: "Organic Greenhouse Tomatoes New 18kg",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 160,
      originalPrice: 300,
      discount: 47,
      rating: 100,
      reviews: 2,
      seller: "Robert's Store",
      badge: "sale",
      category: "groceries",
    },
    {
      id: 2,
      name: "Australian Large Granny Smith Apples",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 350,
      rating: 100,
      reviews: 1,
      seller: "Young Shop",
      badge: "new",
      category: "groceries",
    },
    {
      id: 3,
      name: "Australian Choice Red Capsicum New 3kg",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 266,
      rating: 93,
      reviews: 4,
      seller: "Global Office",
      category: "groceries",
    },
    {
      id: 4,
      name: "Australian Choice Cavendish Bananas",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 266,
      rating: 100,
      reviews: 1,
      seller: "Robert's Store",
      category: "groceries",
    },
    {
      id: 5,
      name: "Choice Australian Broccoli News 20kg",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 666,
      rating: 100,
      reviews: 1,
      seller: "Young Shop",
      category: "groceries",
    },
    {
      id: 6,
      name: "Baby White Washed Potatoes New 15kg",
      image: "/image/slider3.png",
      secondImage: "/image/slider3.png",
      price: 300,
      rating: 100,
      reviews: 1,
      seller: "Robert's Store",
      category: "groceries",
    },
  ],
  smartwatch: [
    {
      id: 7,
      name: "Apple Watch Series 9 GPS 45mm",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 429,
      originalPrice: 499,
      discount: 14,
      rating: 95,
      reviews: 128,
      seller: "Tech Store",
      badge: "sale",
      category: "smartwatch",
    },
    {
      id: 8,
      name: "Samsung Galaxy Watch 6 Classic",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 399,
      rating: 92,
      reviews: 85,
      seller: "Samsung Official",
      badge: "new",
      category: "smartwatch",
    },
    {
      id: 9,
      name: "Garmin Forerunner 965 GPS",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 599,
      rating: 98,
      reviews: 67,
      seller: "Sports Tech",
      category: "smartwatch",
    },
    {
      id: 10,
      name: "Fitbit Versa 4 Health & Fitness",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 199,
      originalPrice: 249,
      discount: 20,
      rating: 88,
      reviews: 156,
      seller: "Fitness Hub",
      badge: "sale",
      category: "smartwatch",
    },
    {
      id: 21,
      name: "Amazfit GTR 4 Smart Watch",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 199,
      rating: 90,
      reviews: 45,
      seller: "Amazfit Store",
      category: "smartwatch",
    },
    {
      id: 22,
      name: "Huawei Watch GT 3 Pro",
      image: "/placeholder.svg?height=300&width=300",
      secondImage: "/placeholder.svg?height=300&width=300",
      price: 329,
      originalPrice: 399,
      discount: 18,
      rating: 89,
      reviews: 67,
      seller: "Huawei Official",
      badge: "sale",
      category: "smartwatch",
    },
  ],
  computer: [
    {
      id: 11,
      name: "MacBook Pro 14-inch M3 Chip",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 1999,
      originalPrice: 2199,
      discount: 9,
      rating: 96,
      reviews: 89,
      seller: "Apple Store",
      badge: "sale",
      category: "computer",
    },
    {
      id: 12,
      name: "Dell XPS 13 Plus Laptop",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 1299,
      rating: 91,
      reviews: 124,
      seller: "Dell Official",
      badge: "new",
      category: "computer",
    },
    {
      id: 13,
      name: "Gaming Desktop RTX 4080 32GB RAM",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 2499,
      rating: 94,
      reviews: 76,
      seller: "Gaming Pro",
      category: "computer",
    },
    {
      id: 14,
      name: "iPad Pro 12.9-inch M2 Chip",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 1099,
      originalPrice: 1199,
      discount: 8,
      rating: 93,
      reviews: 203,
      seller: "Tech World",
      badge: "sale",
      category: "computer",
    },
    {
      id: 23,
      name: "ASUS ROG Zephyrus G14 Gaming Laptop",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 1499,
      originalPrice: 1699,
      discount: 12,
      rating: 95,
      reviews: 87,
      seller: "ASUS Store",
      badge: "sale",
      category: "computer",
    },
    {
      id: 24,
      name: "Microsoft Surface Laptop 5",
      image: "/image/slider1.png",
      secondImage: "/image/slider1.png",
      price: 1299,
      rating: 90,
      reviews: 65,
      seller: "Microsoft Store",
      category: "computer",
    },
  ],
  sport: [
    {
      id: 15,
      name: "Nike Air Max 270 Running Shoes",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 150,
      originalPrice: 180,
      discount: 17,
      rating: 89,
      reviews: 245,
      seller: "Nike Store",
      badge: "sale",
      category: "sport",
    },
    {
      id: 16,
      name: "Adidas Ultraboost 22 Sneakers",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 190,
      rating: 92,
      reviews: 178,
      seller: "Adidas Official",
      badge: "new",
      category: "sport",
    },
    {
      id: 17,
      name: "Wilson Pro Staff Tennis Racket",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 249,
      rating: 95,
      reviews: 67,
      seller: "Sports Equipment",
      category: "sport",
    },
    {
      id: 18,
      name: "Under Armour Gym Bag 40L",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 89,
      originalPrice: 120,
      discount: 26,
      rating: 87,
      reviews: 134,
      seller: "Under Armour",
      badge: "sale",
      category: "sport",
    },
    {
      id: 19,
      name: "Yoga Mat Premium Non-Slip 6mm",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 45,
      rating: 91,
      reviews: 289,
      seller: "Wellness Store",
      category: "sport",
    },
    {
      id: 20,
      name: "Resistance Bands Set with Handles",
      image: "/image/slide2.png",
      secondImage: "/image/slide2.png",
      price: 29,
      originalPrice: 39,
      discount: 26,
      rating: 88,
      reviews: 156,
      seller: "Fitness Pro",
      badge: "sale",
      category: "sport",
    },
  ],
};

export const categories = [
  { id: "groceries", label: "Groceries" },
  { id: "smartwatch", label: "Smart Watch" },
  { id: "computer", label: "Computer" },
  { id: "sport", label: "Sport" },
];
