[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# إعدادات مهمة جداً للـ routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
  force = false
  
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image*"
  status = 200
